#!/usr/bin/env ansible-playbook
# This is a playbook for setting up a container security testing workstation with CLI only tools
# inside a WSL environment.
# N.B. change the user: variable to whatever user you use.
# Details on usage are https://raesene.github.io/blog/2020/05/31/Custom_Pentest_Distributions_With_WSL2/


---
- name: Setup a Container Security Ubuntu Machine
  hosts: localhost
  become: yes
  vars:
    user: root


  tasks:
  - import_tasks: base_container_tasks.yml