---
# Installs [Starship](https://starship.rs/) prompt
- name: Install Starship prompt
  environment:
    HOME: "/home/{{user}}"
  shell: |
    curl -fsSL https://starship.rs/install.sh | sh -s -- -y
  args:
    executable: /bin/sh
  register: starship_install
  changed_when: starship_install.stdout.find("starship") != -1
  failed_when: starship_install.stdout.find("starship") == -1

- name: Copy starship.toml file into place
  ansible.builtin.copy:
    src: "files/starship/starship.toml"
    dest: "/home/{{ user }}/.config/starship.toml"
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: '0644'

- name: Add Starship initialization to .bashrc
  lineinfile:
    path: "/home/{{ user }}/.bashrc"
    line: 'eval "$(starship init bash)"'
    state: present
    create: yes
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: '0644'
