---
# Installs [Starship](https://starship.rs/) prompt
- name: Install Starship prompt
  become: yes
  become_user: "{{user}}"
  environment:
    HOME: "/home/{{user}}"
  shell: |
    curl -fsSL https://starship.rs/install.sh | bash -s -- -y
  args:
    executable: /bin/bash
  register: starship_install
  changed_when: starship_install.stdout.find("starship") != -1
  failed_when: starship_install.stdout.find("starship") == -1
  notify: update bashrc

- name: Copy starship.toml file into place
  ansible.builtin.copy:
    src: "files/starship/starship.toml"
    dest: "/home/{{ user }}/.config/starship.toml"
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: '0644'
  

