name: Build & Push Docker Image

on:
  push:
    branches: [ main ]


jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - name: Docker Login
      run: echo ${{secrets.DOCKER_PASSWORD}} | docker login -u raesene --password-stdin
    - name: install docker python library
      run: sudo pip3 install docker
    - name: run the Image playbook
      run: ansible-playbook docker_container_sec_workstation.yml
    - name: Stop the Docker container
      run: docker stop base
    - name: commit to an image
      run: docker commit base raesene/container_security_tools
    - name: push the image
      run: docker push raesene/container_security_tools

