# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-20.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: azure/docker-login@v1
      with:
        username: ${{ secrets.DOCKER_PASSWORD }}
        password: ${{ secrets.DOCKER_USERNAME }}
    - uses: actions/checkout@v2
    - name: install docker python library
      run: sudo pip3 install docker
    - name: run the Image playbook
      run: ansible-playbook docker_container_sec_workstation.yml
    - name: Stop the Docker container
      run: docker stop base
    - name: commit to an image
      run: docker commit base raesene/container_security_tools
    - name: push the image
      run: docker push raesene/container_security_tools

