name: Test CLI Playbook

on: [push]

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v1
    - name: Install Ansible
      run: apt install -y ansible
    - name: Run a multi-line script
      run: ansible-playbook cli_container_sec_workstation.yml
