name: Test CLI Playbook

on: [push]

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v1
    - name: Install Ansible
      run: sudo apt update && sudo apt install -y ansible
    - name: Remove Moby Docker
      run: sudo apt remove moby-buildx moby-cli
    - name: Run the CLI Container Playbook
      run: ansible-playbook cli_container_sec_workstation.yml
